name: code_margerita
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  get: ^4.6.3
  introduction_screen: ^3.0.1
  highlight_text: ^1.3.0
  geolocator: ^8.2.1
  twilio_flutter: ^0.0.9
  bubble: ^1.2.1
  dialog_flowtter: ^0.3.3
  get_storage: ^2.0.3
  permission_handler: ^10.0.0
  agora_rtc_engine: ^5.2.0
  font_awesome_flutter: ^10.1.0
  speech_to_text: ^5.6.1
  firebase_core:
  firebase_auth:
  cloud_firestore: ^3.1.18
  firebase_storage: ^10.3.10

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/pizza100-358205-90129ad9e974.json



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
